### ISSUE TITLE
Interp after ev does not work?

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/postgkyl#1]
Seem like applying ev to a DG field (so all components are modified) and the doing an interpolation results in an error. For example, the following command does not work with the attached BP file:

`pgkyl -f s1-recovery-dg-diff_f_0.bp ev "f0 -3.8 exp *" interp`

(Unzip the file as github does not allow uploading bp files)

[s1-recovery-dg-diff_f_0.bp.zip](https://github.com/ammarhakim/postgkyl/files/3801613/s1-recovery-dg-diff_f_0.bp.zip)

**Comment by manauref** [comment]
I always thought it was necessary to interp first.

**Comment by ammarhakim** [comment]
No need to interp first. For example, all I want to do is rescale the expansion coefficients and then do something with them. Here, in particular, I want to subtract them from another DG field and then compute sum of squares (L2 norm). Just rescaling all components via "ev" should not cause postgkyl to barf.

**Comment by pcagas** [comment]
'ev' should now be passing metadata to the resulting data set so 'interp' can be used after 'ev'
