### ISSUE TITLE
Saving multiple files

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/postgkyl#10]
We allow reading multiple files and performs ops on them. For example, we can read 100s of files, integrate them 1 direction and apply FFT and animate. However, I would like to save all the 100s of the FFTs to bp files for future use. So the "write" command would need to examine the active datasets and write all of them out. For example:

`pgkyl -f "inp_elc_[0-9]*.bp" interp write -f elc_interp`

In this case the output should be "ecl_interp_0.bp", "ecl_interp_1.bp" etc 

Should not be hard to do.

**Comment by pcagas** [comment]
Implemented
