### ISSUE TITLE
The ev command seems to be broken

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/postgkyl#117]
It seems ev is broken. Selecting data-set, either using f[0] etc or using tags is not working.

**Comment by manauref** [comment]
Can you give an example? I've encountered some problems too, but have gotten it to work most of the time.

**Comment by pcagas** [comment]
Can't replicate this
`pgkyl 10m_par_firehose_grad_closure-elc_0.gkyl 10m_par_firehose_grad_closure-elc_1.gkyl ev 'f[0] f[1] -' pl`
![image](https://github.com/ammarhakim/postgkyl/assets/15108613/8f420fe3-eddd-40e0-98e6-16c0a4a6b204)

**Comment by pcagas** [comment]
This problem only appears when the number of dimensions is bigger than 1. Fixed in PR #118
