### ISSUE TITLE
Tags for datasets

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/postgkyl#12]
The goal is to get to diagnostic/analysis commands in pgkyl (pg). For this, the present infrastructure of pg is not adequate, as a diagnostic command may need multiple inputs and produce multiple outputs.

So, I suggest that we add a "tag" feature to pgkyl. So:

pgkyl -f elc_vel_10.bp -t "vel" -f field_10.bp -t "field" 

Now, commands in the chain can use the tags "vel" "field" to access the data. This subverts the stack and allows accessing data directly. If the tag is attached to a set of files (read by a wild-card) then the tag fetch method would return a list (it would always return a list).

So, a command that computes say upar from velocity and field would do:

```
def calcupar():
   velList = dataStack.getTag("vel")
   fieldList = dataStack.getTag("field")
```
Now, the command would loop over these lists, do its job and put back on the stack files, optionally tagging them also.

This allows one to have multiple commands that take tags, and the order in which the files are specified in the -f series would be irrelevant. 

Existing commands in the pgkyl chain would not care about tags and work-as-is, passing on the tags to the next command as-is. So everything would flow smoothly. So say one does:

pgkyl -f elc_vel_10.bp -t "vel" -f field_10.bp -t "field"  interp

Now, the interp command does not care about tags so the output of the interp command would be the tags attached to its output which would be the interpolated velocity and field data.

With this then people who want to write diagnostic commands can do so. The tag feature will open up many possibilities not possible at present (PnPaP).

For example, the dataset command can take tags as an option instead of the horrible and hard to use -i option to make some sets active etc. So:

pgkyl -f a.bp -t "a" -f b.bp -t "b" -f c.bp -t "c" dataset -t c interp pl

would interpolate "c" tagged fields and plot them.

**Comment by pcagas** [comment]
Starting a new branch `tagreorg` to work on this. This will significantly change the behavior of the important parts of the code and allow for additional features especially considering wildcard loading.
