### ISSUE TITLE
Updating postgkyl installation

### ISSUE THREAD

**Issue by pcagas** [ammarhakim/postgkyl#120]
Our current system of installing the entire `postgkyl` package through conda does not seem sustainable.

The goal of this issue is to track the migration to a new setup with PR #119.

**Comment by pcagas** [comment]
Related to issue #115

**Comment by ammarhakim** [comment]
I am trying to follow the instructions to get pgkyl on my Ubuntu laptop. Here are some issues I have uncovered:

- I needed to update to latest conda version. 
- The README has the wrong name of the yaml file. It should be `environment.yml` and not with the yaml extension.
-  The instruction to init the conda env is missing. I had to do: `conda init fish`. Other shells will have different shell-names to use. This needs to be clarified.

After running pip (which seems to complete successfully) I got the following error:

```
gandalf@valinor ~/r/g/postgkyl> pgkyl --help                            (pgkyl) 
Traceback (most recent call last):
  File "/home/gandalf/miniconda3/envs/pgkyl/bin/pgkyl", line 5, in <module>
    from postgkyl.pgkyl import cli
ImportError: bad magic number in 'postgkyl': b'\x03\xf3\r\n'

```
I realized that this was happening as postgkyl is also in my PYTHONPATH and this is confusing the system. I had to remove PYTHONPATH from my bashrc and restart the shell. Then things seem to work.

I suggest updating the docs with this info also.

**Comment by ammarhakim** [comment]
Can this issue now be closed? We still need to fix the README as described above, I think. Plus a few other people should try the README instructions.

**Comment by pcagas** [comment]
README has been updated in #127

**Comment by pcagas** [comment]
RTD documentation is updated in https://github.com/ammarhakim/gkyl-doc/pull/17
