### ISSUE TITLE
'-s' flag not working properly

### ISSUE THREAD

**Issue by kltrbrds** [ammarhakim/postgkyl#132]
[test_frequencies.bp.zip](https://github.com/ammarhakim/postgkyl/files/15000698/test_frequencies.bp.zip)
There seems to be an issue with the '-s' or '--scatter' flag returning `TypeError: plot() got multiple values for argument 'args'`. One possible contributor is that '-s' seems linked to both scatter and squeeze, though removing the '-s' flag from Line 41 of postgkyl/src/postgkyl/commands/plot.py and running with '--scatter' does not seem to fix the problem.
The attached .bp file contains the eigenvalues matching the `iso-1-wave` example from https://ammar-hakim.org/sj/je/je34/je34-linear-dispersion.html and should match the corresponding dispersion plot when run using `pgkyl test_frequencies.bp/ val2coord -x0 -y 3::2 pl -f0 -s`.

**Comment by pcagas** [comment]
There was an issue in passing arguments to `plot`. It has been resolved in PR #133
