### ISSUE TITLE
Package conflicts found when creating the new environment on stellar

### ISSUE THREAD

**Issue by dingyunl** [ammarhakim/postgkyl#135]
I was trying to install the updated postgkyl on stellar. I started with a clean state (i.e. only anaconda is loaded, no paths or modules loaded in bashrc, no old conda envs), but package conflicts are found in the step of creating the new environment with the command below:
`conda env create -f environment.yml`
The error message is attached in the file.
[error_message.txt](https://github.com/user-attachments/files/15673265/error_message.txt)

**Comment by manauref** [comment]
we removed some stuff that was in the $HOME directory, including a .condarc file, which might've been causing this. The installation worked then.

There are still warnings and errors that show up, but pgkyl plots still.

**Comment by pcagas** [comment]
@manauref what kind of warnings?

**Comment by manauref** [comment]
Like this
```
Successfully built postgkyl
Installing collected packages: sympy, numpy, ndindex, click, scipy, matplotlib, blosc2, tables, postgkyl
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 1.26.4 which is incompatible.
python-lsp-black 1.2.1 requires black>=22.3.0, but you have black 0.0 which is incompatible.
Successfully installed blosc2-2.6.2 click-8.1.7 matplotlib-3.9.0 ndindex-1.8 numpy-1.26.4 postgkyl-1.7.1.dev87+gf876908 scipy-1.13.1 sympy-1.12.1 tables-3.9.2
```
but like I said, plotting works despite it
