### ISSUE TITLE
Some internal commands have signature changes (such as changes to prim_vars.py not propagating to pressure_diagnostics.py)

### ISSUE THREAD

**Issue by JunoRavin** [ammarhakim/postgkyl#142]
It appears that in the process of doing some type-checking and more standardized function signatures, some internal methods signatures have not propagated to other methods which utilize these functions. 

For example, pressure_diagnostics utilizes primitive variable computations such as here:
https://github.com/ammarhakim/postgkyl/blob/main/src/postgkyl/tools/pressure_diagnostics.py#L202

but it seems that this line needs to be changed to
` p_grid, p_values = diag.get_pij(species_data)`

to take into account the new function signatures of the prim_vars.py methods. Happy to help fix these issues or can defer to @pcagas with the refactor for stronger type-checking.

**Comment by pcagas** [comment]
Good catch, @jimmy! Thank you. Yeah, I've been working on some of these issues recently in a branch and adding tests. I guess the best way would be that if you find something broken like this, you can quickly patch it so it works in the main branch and I'll then merge it to my refactoring and add types and stuff. I'm of course open to suggestions!
