### ISSUE TITLE
Tool to create a summary or "table of contents" of files written by a gkyl sim

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#17]
Currently a simulation may write thousands of files, some chosen via input file but others written by default. The large number of files makes it difficult to browse or see what's available without a priori knowledge of what Gkeyll writes (which only developers tend to have).

It'd be good to have a tool (gkyl tool or postgkyl command) that gives a summary of the diagnostics in a folder. For example, lets assume that a simulation outputted many momenta and energy density, and field files like:
sim_elc_M1i_#.bp
sim_elc_M2_#.bp
sim_field_#.bp
The latter is written out by default. Suppose the user doesn't know sim_field_#.bp were written and there are thousands of files so that it is hard to "ls *.bp" the directory and browse. How about we provide a summary one of two ways:

A) Something like `pgkyl list`, which would return
sim_elc_M1i
sim_elc_M2
sim_field

B) Something like `pgkyl info`, which would return a list of meta data for each of these 3 types of files (like a summary version of `pgkyl -f file.bp info`), but not a list of pgkyl info for all files:
Dataset **sim_elc_M1i**
- Number of components: 4
- Number of dimensions: 1
- Grid: (uniform)
  - Dim 0: Num. cells: 32; Lower: 0.000000e+00; Upper: 1.570796e+01
- Maximum: 2.579557e-18 at (0,) component 2
- Minimum: -1.805154e-18 at (0,) component 0
- DG info:
  - Polynomial Order: 1
  - Basis Type: serendipity (modal)
- Created with Gkeyll:
  - Changeset: b6f13edc2f7f+
  - Build Date: Dec 26 2020 15:41:26
  
 Dataset **sim_elc_M2**
- Number of components: 2
- Number of dimensions: 1
- Grid: (uniform)
  - Dim 0: Num. cells: 32; Lower: 0.000000e+00; Upper: 1.570796e+01
- Maximum: 1.555630e-01 at (0,) component 0
- Minimum: -1.895426e-19 at (0,) component 1
- DG info:
  - Polynomial Order: 1
  - Basis Type: serendipity (modal)
- Created with Gkeyll:
  - Changeset: b6f13edc2f7f+
  - Build Date: Dec 26 2020 15:41:26

Dataset **sim_field**
- Number of components: 16
- Number of dimensions: 1
- Grid: (uniform)
  - Dim 0: Num. cells: 32; Lower: 0.000000e+00; Upper: 1.570796e+01
- Maximum: 1.405144e-03 at (7,) component 10
- Minimum: -1.405144e-03 at (23,) component 10
- DG info:
  - Polynomial Order: 1
  - Basis Type: serendipity (modal)
- Created with Gkeyll:
  - Changeset: b6f13edc2f7f+
  - Build Date: Dec 26 2020 15:41:26

**Comment by ammarhakim** [comment]
I am not sure why we can't use ls for this? I don't there is any need to add any tool to the pgkyl for this. Use ls and info. Info could tell us file meta-data if needed. Unless there is something missing I doubt this is useful. Clarify please.

**Comment by manauref** [comment]
Can you show me how to use ls or info to produce the example outputs I gave above (in a directory with many frames)?

**Comment by pcagas** [comment]
Is the goal to essentially list all the unique file names without frame numbers?

**Comment by manauref** [comment]
@pcagas yes, the idea is to give the user a list of unique file names so they can become aware of what's there. Whether to provide the 'info' or not is up to debate.

Ammar showed that we can provide the simple list (without info) in the terminal with:

ls rt-two-stream-*.bp | grep -v “restart.bp” | sed ‘s/_[0-9]*.bp*//’ | uniq

I still think it'd be good to have a tool or a command that does this kind of thing and doesn't require the user to be a scripting master.

**Comment by pcagas** [comment]
The first functionality has been added; the new command is called `listoutputs`

![image](https://user-images.githubusercontent.com/15108613/105905747-cfeae680-5ff0-11eb-9b2d-213a032f04fc.png)

**Comment by pcagas** [comment]
I don't think the second option is needed as any user can simply select the file of choice (especially now using `listoutputs`) and call `info` on it, e.g. `pgkyl rt-two-stream-p1_elc_0.bp info`

**Comment by manauref** [comment]
Awesome, thanks Petr. Yes I agree, we can forget about the second option for now.
