### ISSUE TITLE
Make it so that animate -f puts multiple data groups on the same figure/animation

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#26]
Change the meaning of -f in animate to match that in plot (specify figure) so that:
- It's consistent with plot. As animate/plot capabilities increase it'd be good to have the same instructions for both.
- We can have multiple groups of data shown on the same animation (only makes sense for 1D animations).

For example, something like
pgkyl "simName_elc_M0_[0-9]*.bp" "simName_ion_M0_[0-9]*.bp" interp anim -f0

**Comment by pcagas** [comment]
This has been now enabled but requires using tags:
`pgkyl 'simName_elc_M0_[0-9]*.bp' -t elc 'simName_ion_M0_[0-9]*.bp' -t ion interp anim -f0`
The `--float` which previously had the short version `-f` now needs to be fully spelled out.

There is still an issue with labels in `animate` but I am closing this issue and leaving #16 open.

**Comment by manauref** [comment]
Awesome, thanks Petr.
Would the labels work if you specify labels explicitly, like

pgkyl 'simName_elc_M0_[0-9]*.bp' -t elc -l elc 'simName_ion_M0_[0-9]*.bp'
-t ion -l 'ion' interp anim -f0

or after interp-ing each data set separately like

pgkyl 'simName_elc_M0_[0-9]*.bp' -t elc 'simName_ion_M0_[0-9]*.bp' -t ion
activ -t elc interp -t elcI -l 'elc' active -t ion interp -t ionI -l 'ion'
activ -t elcI,ionI anim -f0

?

**Comment by pcagas** [comment]
@manauref, yes this is absolutely the plan! I ran into weird issues when trying this and will need more time to finish it. I'm keeping #16 open until I add it.
