### ISSUE TITLE
NERSC's Cori doesn't seem to like info symbols

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#29]
Just cloned the postgkyl repo in my Cori directory.

When I try to info a file I get:

**pgkyl gk36-wham1x2v_elc_0.bp info**
```
Traceback (most recent call last):
  File "/global/homes/m/mana/cori/gkeyll/postgkyl/pgkyl", line 4, in <module>
    import postgkyl.pgkyl
  File "/global/u1/m/mana/cori/gkeyll/postgkyl/postgkyl/__init__.py", line 31, in <module>
    from . import data
  File "/global/u1/m/mana/cori/gkeyll/postgkyl/postgkyl/data/__init__.py", line 2, in <module>
    from .data import Data
  File "/global/u1/m/mana/cori/gkeyll/postgkyl/postgkyl/data/data.py", line 582
SyntaxError: Non-ASCII character '\xe2' in file /global/u1/m/mana/cori/gkeyll/postgkyl/postgkyl/data/data.py on line 582, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

And lookin at data.py line 582 with vim I see:
<img width="534" alt="Screen Shot 2021-04-25 at 6 00 03 PM" src="https://user-images.githubusercontent.com/2220456/116015978-164fe180-a5f0-11eb-8807-f5b5ac28d895.png">

This however is not a problem when using pgkyl from Conda. Is there another dependency we need to install when using pgkyl from source for these ```info``` symbols to work?

**Comment by manauref** [comment]
One also needs to install msgpack-python when installing postgkyl from source. I added this to the docs.

**Comment by manauref** [comment]
Just want to add that my problem on Cori seemed to involve more than just installing this dependency. There's something puzzling going on with aliases on Cori, which causes this error to appear if I activate my Conda environment through an alias, but not if I simply type the commands into the terminal or use a bash script.

**Comment by pcagas** [comment]
These symbols look nice but are otherwise 100% optional. If they are causing issues, we can get rid of them.
