### ISSUE TITLE
Load multiple datasets from the same file

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#33]
If one uses the "twoFile" option in diagnostics (probably will be renamed) it produces a `gridDiagnostics` file that has multiple grid diagnostics. It'd be good to be able to load multiple ones by just listing them, such as
```
pgkyl <simName>_ion_gridDiagnostics_0.bp -d M0,M2 interp pl
```
instead of having to use the lengthier
```
pgkyl <simName>_ion_gridDiagnostics_0.bp -d M0 <simName>_ion_gridDiagnostics_0.bp -d M2 interp pl
```

**Comment by pcagas** [comment]
You can already do:
`pgkyl <simName>_ion_gridDiagnostics_0.bp -d M0 -d M2 interp pl`
Adding the comma separation should be simple if we want to change taht

**Comment by pcagas** [comment]
The comma-separated input now works as well (as is the case for many other pgkyl commands; good call).
`pgkyl <simName>_ion_gridDiagnostics_0.bp -d 'M0,M2' interp pl`
