### ISSUE TITLE
module 'numpy' has no attribute 'asscalar'

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#43]
A user who installed postgkyl through conda yesterday encountered this error

"AttributeError: module 'numpy' has no attribute 'asscalar'"

when plotting the distribution function of our quickstart example with 

pgkyl vm-damp_elc_0.bp interpolate plot.

It was temporarily fixed by downgrading numpy from 1.23.0 to 1.22.3. I search the code for 'asscalar' and couldn't find anything. Is this a problem with another python package (version), or are we implicitly requesting asscalar somewhere?

**Comment by pcagas** [comment]
`asscalar` is not used anywhere in postgkyl so possibly an issue with another package? Hard to tell without more information.

**Comment by pcagas** [comment]
This is an issue that was resolved in a new version of the ADIOS Python wrapper. The solution is to switch to the `conda-forge` version of the Python ADIOS. I have updated our conda recipes and the documentation accordingly.
