### ISSUE TITLE
--yscale doesn't work with plot -g

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#48]
the command 
```
pgkyl "l3-gkLTX-1x2v-p1_elc_gridDiagnostics_[0-9]*.bp" -d Tpar activ -i :6 interp -b ms -p1 collect sel --z0 : pl -g1 -x 'z (m)' -y '$T_{\parallel e}$ (eV)' --clabel 'Time (s)' --yscale 6.2422e18
```
produces the image below, so I suspect it is scaling the x axis instead, and if you try with ```--xscale``` nothing happens.

<img width="609" alt="Screen Shot 2022-10-03 at 3 16 22 PM" src="https://user-images.githubusercontent.com/2220456/193695722-be665677-1942-4553-bdc4-22e960edc148.png">

**Comment by pcagas** [comment]
Fixed. I have also changed the colormap to Inferno from Viridis. Inferno was originally decided to be the pgkyl colormap and it's better to be consistent.
