### ISSUE TITLE
Recovery plotting enhancements

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/postgkyl#5]
1. We can extend the recovery scheme to plot multidimensional data by recovering direction by direction. In 2D this would result in a 9-point stencil, for example. Very likely we don't need to do recovery plotting in > 3D. But we may want to support slicing and then recovering the sliced data.
2. We should add options to the recovery plotter (even in 1D) to take in BCs. For example, Robin BCs or periodic etc. This would then use the constrained two-cell recovery in the skin cell to make the plots.

**Comment by pcagas** [comment]
This should be part of a major refactor of the whole DG part of postgkyl

**Comment by pcagas** [comment]
#6
