### ISSUE TITLE
Numpy attribute asscalar is deprecated

### ISSUE THREAD

**Issue by pjujeczko** [ammarhakim/postgkyl#51]
Hello, I have installed postgkyl today, but there is a problem with a deprecated "asscalar" attribute when I want to invoke pgkyl. 

> Traceback (most recent call last):
 >  File "/net/people/plgpjujeczko/pgkyl/bin/pgkyl", line 11, in <module>
>     sys.exit(cli())
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/click/core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/click/core.py", line 1690, in invoke
>     rv.append(sub_ctx.command.invoke(sub_ctx))
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/postgkyl/commands/load.py", line 95, in load
>     data.add(Data(fileName=fn, tag=kwargs['tag'],
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/postgkyl/data/data.py", line 96, in __init__
>     self._loadFrame(zs, comp)
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/postgkyl/data/data.py", line 196, in _loadFrame
>     self.meta['changeset'] = adios.attr(fh, 'changeset').value.decode('UTF-8')
>   File "adios.pyx", line 1751, in adios.attr.value.__get__
>   File "/net/people/plgpjujeczko/pgkyl/lib/python3.9/site-packages/numpy/__init__.py", line 311, in __getattr__
>     raise AttributeError("module {!r} has no attribute "
> AttributeError: module 'numpy' has no attribute 'asscalar'

It could be easily fixed I guess since "asscalar(obj)" may be changed to obj.item(), but I don't know where the problem lays (I couldn't find adequate line in mentioned files). If one could tell me where should I search for that wrongful asscalar I would be grateful.

Regards!

**Comment by manauref** [comment]
@pjujeczko this is fixed in pull request #50, which @ammarhakim @pcagas should be merging any minute now.

**Comment by pjujeczko** [comment]
That's great. Sorry for missing issue #43 and thanks for the reply!

**Comment by pcagas** [comment]
No worries! The error is on my side, I did mark the issue as resolved already and but wanted to pack more bug fixes into the pull request. It will certainly be merged today and I will create a new conda release right after that.

**Comment by pcagas** [comment]
A new version of postgkyl which uses a version of ADIOS where this bug has been fixed has been just pushed to our channel.

**Comment by GermainRV** [comment]
If anyone else has this error when importing postgkyl in python, it also worked for me by installing another version of numpy:
`pip install numpy==1.21.2`

**Comment by pcagas** [comment]
This is a dependency problem so I'm marking this as `wontfix`.
