### ISSUE TITLE
Plotting with option -f0 is no longer working for multi-block grids

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/postgkyl#75]
When using plot -f0 seems that all plots are overlaying each other even when the grids are actually different. To see this problem run the regression test in G0:
 
  ./build/regression/rt_euler_multiblock 

Then plot:

 pgkyl euler_multiblock_1_b0.gkyl euler_multiblock_1_b2.gkyl euler_multiblock_1_b1.gkyl sel -c0 pl -a -f0

This makes a single plot with all plots mushed on top of each other. This is  a bug and it was not doing this before.

**Comment by pcagas** [comment]
fixed in #77
