### ISSUE TITLE
extractinputfile command is not working

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/postgkyl#8]
Turns out the extractinputfile command is not working. I checked that the attribute is read properly but the call fails on encInp = ctx.obj['dataSets'][s].inputfile on line line 15, in extractinput.

Also, bpls -a shows the attribute and I can get the base64 encoded file from the postgkyl Python package. So the bug is in extractinputfile or the code that computes the dataSets.

This should be reproducible from any BP file generated with the latest (as of April 13th 2020 11:00 am) commit of Gkeyll.

**Comment by pcagas** [comment]
Should be working now

**Comment by ammarhakim** [comment]
Tested and it works now.
