### ISSUE TITLE
Grid file read needs to append path

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#9]
Suppose I'm in directory
`currDir = ./`
but my data is in 
`dataDir = ./run/`
I'm running a python script in `currDir` that reads fileName="./run/run_elc_0.bp". Postgkeyll reads the 'grid' attribute from fileName and finds gridFile="run_grid_elc.bp". Then it fails when it tries to read it (line 220 of postgkyl/data/gdata.py) because it is missing the path; it should instead try to read gridFile="./run/run_grid_elc.bp".

Can we fix this little thing? 
In my own wrappers I solved it as follows:
```
def getGridFileName(dataFile):
  hF       = ad.file(dataFile)
  gridFile = hF.attr['grid'].value
  hF.close()
  #.Append the rest of the file address if necessary.
  filePath = dataFile.rsplit('/',maxsplit=1)
  if len(filePath) > 1:
    gridFile = filePath[0]+'/'+gridFile.decode('UTF-8')
  else:
    gridFile = gridFile.decode('UTF-8')
  return gridFile
```

**Comment by ammarhakim** [comment]
Please don't assign tasks to me :) Thanks.

Yes, I agree that pgkyl should use path relative to the one used in the -f specification

**Comment by manauref** [comment]
I'm always a little wary of editing pgkyl, but I could try myself, if
that's ok with Petr.

**Comment by ammarhakim** [comment]
Everyone in the team should feel empowered to change and improve things. If one is not sure one should do it in a branch and submit a pull request. Bad changes can always be undone.

**Comment by pcagas** [comment]
Ammar is 100% right. Improvements and bug-fixes from the other members of the team are very much encouraged! I'll be happy to discuss aspects of the code to enable this.

This issue has been fixed.
